# Generated by Django 6.0.2 on 2026-02-10 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_info', models.CharField(max_length=200, verbose_name='Información del Vehículo')),
                ('plate', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección de Entrega')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Estimada de Recepción')),
                ('comments', models.TextField(blank=True, verbose_name='Notas Especiales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=200, verbose_name='ID del Evento en Google Calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'conductores'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transports', to=settings.AUTH_USER_MODEL, verbose_name='Conductor Asignado')),
            ],
            options={
                'verbose_name': 'Solicitud de Traslado',
                'verbose_name_plural': 'Solicitudes de Traslado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Showroom',
        ),
    ]
