# Generated by Django 6.0.2 on 2026-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transportschedule_delete_car_delete_showroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportschedule',
            old_name='address',
            new_name='dropaddress',
        ),
        migrations.AddField(
            model_name='transportschedule',
            name='pickaddress',
            field=models.TextField(default='', verbose_name='Dirección de Recogida'),
            preserve_default=False,
        ),
    ]
